services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.main
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: ADMIN_IDS
        sync: false
      - key: WALLET_PAY_API_KEY
        sync: false
      - key: LOW_MEMORY_MODE
        value: "True"
  
  - type: redis
    name: redis
    ipAllowList: [] # internal only
    plan: free # or starter
